var betSlipML = {
    timeout: "很抱歉，您的申请处理已超时，请重试。",
    error: "很抱歉，错误产生。请拨打+44 1782 684 657联系我们，我们的客服人员将非常乐意为您提供帮助。或者，您也可访问bet365主页",
    closedorsuspended: "抱歉，此页无法使用，投注已关闭或终止。",
    duplicateselection: "投注单上已添加此投注项",
    maxselections: "投注项数量已达到上限",
    checkmembers: "<BR/>请核对会员区确认投注是否成功。",
    incompatibleselections: "这些投注项与您投注单上已有的投注项不相容。",
    pleaselogin: "请登录使用最高投金选项。",
    stake: "本金",
    unitstake: "单位本金",
    towin: "预计彩金",
    tomanyselection: "无法向投注单添加这些投注项，投注单上选项过多。",
    ustotesinglesinvalid: "单位本金必须以每USD1.00进行，每个奖池类型的最低总投注金为USD2.00。",
    ustotecastsinvalid: "最低单位本金为USD2.00，因此单位本金必须为整数。",
    selection: "投注项",
    invalidlogin: "我們無法識別您的信息",
    loginorjoinnow: '请登录进行投注，或 <a id="bsjn" href="#">立即加入<\/a>.',
    teasersminselections: "让分复式投注选项必须超过最低许可。",
    incompatibleselectionsclear: "添加该投注将清除您现有的投注单",
    incompatibleselectionsremove: "您的投注单包含<br />独赢/位置/Show/科卡士/三重彩/连赢/指定连赢位置/trifecta/superfecta投注项，且与{0}式投注要求不相容。这些投注项将被删除。",
    pleaseenterstakeorrisk: "请输入所有投注项的投注额",
    ifbetminselections: "条件式投注必须有至少2个选项。",
    pleaseenterstake: "请输入投注。",
    insufficientfunds: "您的账户余额不足",
    sp: "SP",
    minstaketote: "Tote Win、位置和独赢及位置的最低单位投注金为£2.00，并以每10p递增。指定连赢位置和三重彩投注金必须以每10p输入，最低总投注金为£2.00。",
    toteperunitstake: "无效投注金：Tote Scoop6仅接受单位本金为2.00GBP的投注。",
    toteinvalidstake: "无效投注金：Tote Quadpot和Placepot投注金必须以每10p输入，最低总投注金为1.00 GBP。",
    pleasecheckmembers: "请查看“我的投注”以确认您已投注成功。",
    currentlynotloggedin: "您当前不是以会员身份登录！",
    processingbet: "正在处理您的投注单。",
    additionalstakereferred: "请耐心等待，您的超额投注请求已经提交给操盘手。",
    logintoplacebet: "请登录进行投注。",
    totejackpotinvalidstake: "无效投注金：Tote Jackpot投注金必须以每50p输入，最低总投注金为1.00 GBP。",
    etoteinvalidstake: "无效投注金：Etote Win、位置和独赢及位置的最低单位投注金为£1.00，并以每1p递增。",
    exactainvalidstake: "无效投注金：指定连赢位置和Trio的最低单位投注金为£1.00，并以每1p递增。",
    bestdividendguarantee: "我们将根据您所做选择的相应两项TAB组织方或我们当前的固定赔率，保证为您赔付最佳分红。",
    cont: "继续",
    engb: "zh-HK",
    addedtobetslip: "添加至投注单",
    lines: "单位",
    incompatibleselectionstitle: "您投注單上的投注項",
    addmore: "添加更多",
    added: "已添加",
    scrollupmessage: "上移至投注单",
    ok: "登录",
    cancel: "取消",
    addtobetslip: "添加至投注单",
    balance: "余额",
    or: "或",
    accept: "接受",
    oddsChanged: "您所选投注项的盘口、赔率或有效性已经产生变化。",
    aamsrejected: "Bet rejected by ADM",
    done: "确定",
    login: "登录",
    referringBet: "投注申请提交中",
    totesuper7perunitstake: "投注无效：Tote Super7的总投注额最低为2.00 GBP，且金额以10p为单位依次递增。",
    matchalertonematch: "获得该比赛的实时提醒",
    matchalertmultiplematch: "获得<span class='BetSlipLiveAlert-Header__Link'>这些比赛<\/span>的实时提醒",
    matchalertonerace: "获得该比赛的实时提醒",
    matchalertmultiplerace: "获得<span class='BetSlipLiveAlert-Header__Link'>这些比赛<\/span>的实时提醒",
    matchalertmultipleevents: "获得<span class='BetSlipLiveAlert-Header__Link'>这些赛事<\/span>的实时提醒",
    confirmingbet: "Confirming Bet",
    callUnsuccessful: "Your call has failed – please call 1800 365 365 to place bet",
    incompatiblectcselectionsclear: "betCall is available for In-Play Singles only. Click OK to clear your betslip and add this new selection",
    free: "免费",
    ausRacingBest: "365最佳",
    ausRacingTopTotePlus: "365最佳Tote+",
    ausRacingTote: "365 Tote",
    ausRacingMidPlus: "365 Mid+",
    ausRacingInternational: "365国际",
    ausRacingToteTooltipToteWin16: "Tote獨贏將提供您Middle Tote外加您彩金的5％。",
    ausRacingToteTooltipTotePlace16: "Tote位置將提供您Middle Tote外加您彩金的5％。",
    ausRacingToteTooltipToteEachWay16: "Tote独赢及位置将提供您Middle Tote外加您彩金的5％。",
    ausRacingToteTooltipToteWin1: "Tote独赢提供您3个国家Tote公布的最佳独赢分红或最终官方赔率，取二者之中较高者。",
    ausRacingToteTooltipTotePlace1: "Tote位置將提供您所有3個國家Tote公布的最佳位置分紅。",
    ausRacingToteTooltipToteWin2: "Tote独赢提供您3个国家Tote公布的最佳独赢分红或最终官方赔率，取二者之中较高者。",
    ausRacingToteTooltipTotePlace2: "Tote位置为您提供Middle Tote及您彩金的5％。",
    ausRacingToteTooltipToteWin8: "Tote獨贏將提供您Middle Tote外加您彩金的5％。",
    ausRacingToteTooltipTotePlace8: "Tote位置將提供您Middle Tote外加您彩金的5％。",
    ausRacingToteTooltipToteEachWay1: "Tote独赢提供您3个国家Tote公布的最佳独赢分红或最终官方赔率，取二者之中较高者。位置部分提供您3个国家Tote公布的最佳位置分红。",
    ausRacingToteTooltipToteEachWay2: "Tote独赢提供您3个国家Tote公布的最佳独赢分红或最终官方赔率，取二者之中较高者。位置部分提供您SuperTAB或NSW TAB公布的最佳位置分红。",
    ausRacingToteTooltipToteEachWay8: "Tote独赢及位置将提供您Middle Tote外加您彩金的5％。",
    freeStake: "（免费）",
    freePartial: "（{0}免费）",
    toreturn: "返還",
    netReturn: "净返还",
    betCredittext: "Use Bet Credits ({0} available)",
    betCreditItemText: '<span class="bs-BetCreditUsing">Using<\/span> {0} Bet Credits',
    betCreditPartialItemText: '<span class="bs-BetCreditUsing">Using<\/span> {0} Bet Credits + {1} {2}',
    betCreditTotals: "{0} Bet Credits",
    betCreditTotalsPartial: "{0} Bet Credits + {1} {2}",
    UsingBetCredits: "使用[X]投注抵用金",
    UsedBetCredits: "已用[X]投注抵用金",
    TotalBetCreditsFreeBetInplayPlusStake: "总投注 {0}投注抵用金 + {1} {2} + {3}滚球盘免费投注",
    TotalBetCreditsFreeBetInplay: "总投注 {0}投注抵用金 + {1}滚球盘免费投注",
    TotalBetCreditsFreeBetPlusStake: "总投注 {0}投注抵用金 + {1} {2} + {3}免费投注",
    TotalBetCreditsFreeBet: "总投注 {0}投注抵用金 + {1}免费投注",
    TotalFreeBetPlusStake: "总投注 {0}免费投注 + {1} {2}",
    TotalFreeBetInplayPlusStake: "总投注 {0}滚球盘免费投注 + {1} {2}",
    TotalBetCreditsPlusStake: "总投注 {0}投注抵用金 + {1} {2}",
    TotalBetCredits: "总投注 {0}投注抵用金",
    TotalFreeBet: "总投注 {0}免费投注",
    TotalFreeBetInplay: "总投注 {0}滚球盘免费投注",
    NetReturnsBetCredits: "净返还不包括投注抵用金",
    NetReturnsFreeBet: "净返还不包括免费投注金额",
    NetReturnsFreeBetInPlay: "净返还不包括滚球盘免费投注金额",
    NetReturnsBetCreditsFreeBet: "净返还不包括投注抵用金和免费投注金额",
    NetReturnsBetCreditsFreeBetInPlay: "净返还不包括投注抵用金和滚球盘免费投注金额",
    BetCreditsFreeBetInplayPlusStake: "{0}投注抵用金 ＋ {1} {2} ＋ {3}滚球盘免费投注",
    BetCreditsFreeBetInplay: "{0}投注抵用金 ＋ {1}滚球盘免费投注",
    BetCreditsFreeBetPlusStake: "{0}投注抵用金 ＋ {1} {2} ＋ {3}免费投注",
    BetCreditsFreeBet: "{0}投注抵用金 ＋ {1}免费投注",
    FreeBetPlusStake: "{0}免费投注 ＋ {1} {2}",
    FreeBetInplayPlusStake: "{0}滚球盘免费投注 ＋ {1} {2}",
    BetCreditsPlusStake: "{0}投注抵用金 ＋ {1} {2}",
    BetCredits: "{0}投注抵用金",
    FreeBet: "{0}免费投注",
    FreeBetInplay: "{0}滚球盘免费投注",
    TotalStake: "总投注 {0}",
    NetReturnTax: "净返还值为税金扣除后的数额",
    SplitError: "您的投注抵用金余额无法分配至所请求的投注。",
    AddSelections: "添加选项",
    edit: "修改"
}